// src/app/templates/ts/angular/src/app/app.component.ts
import { Component } from '@angular/core';
<%- imports %>

const template = require('./app.component.html');

@Component({
    selector: 'app-home',
    template
})
export default class AppComponent {
    welcomeMessage = 'Welcome';

    async run() {
        <%- snippet %>
    }
}
<header class="ms-welcome__header ms-bgColor-neutralLighter ms-u-fadeIn500">
    <img width="90" height="90" src="../../assets/logo-filled.png" alt="<%= projectInternalName %>" title="<%= projectInternalName %>" />
    <h1 class="ms-fontSize-su ms-fontWeight-light ms-fontColor-neutralPrimary">{{welcomeMessage}}</h1>
</header>
<main class="ms-welcome__main">
    <h2 class="ms-font-xl ms-fontWeight-semilight ms-fontColor-neutralPrimary ms-u-slideUpIn20"> Discover what <%= projectInternalName %> can do for you today! </h2>
    <ul class="ms-List ms-welcome__features ms-u-slideUpIn10">
        <li class="ms-ListItem">
            <i class="ms-Icon ms-Icon--Ribbon"></i>
            <span class="ms-font-m ms-fontColor-neutralPrimary">Achieve more with Office integration</span>
        </li>
        <li class="ms-ListItem">
            <i class="ms-Icon ms-Icon--Unlock"></i>
            <span class="ms-font-m ms-fontColor-neutralPrimary">Unlock features and functionality</span>
        </li>
        <li class="ms-ListItem">
            <i class="ms-Icon ms-Icon--Design"></i>
            <span class="ms-font-m ms-fontColor-neutralPrimary">Create and visualize like a pro</span>
        </li>
    </ul>
    <br />
    <br />
    <p class="ms-font-l">Modify the source files, then click <b>Run</b>.</p>
    <div role="button" class="ms-welcome__action ms-Button ms-Button--hero ms-u-slideUpIn20" (click)="run()">
        <span class="ms-Button-label">Run</span>
        <span class="ms-Button-icon"><i class="ms-Icon ms-Icon--ChevronRight"></i></span>
    </div>
</main>

// src/app/templates/ts/react/src/components/app.tsx
import * as React from 'react';
import { Button, ButtonType } from 'office-ui-fabric-react';
import { Header } from './header';
import { HeroList, HeroListItem } from './hero-list';

export interface AppProps {
    title: string;
}

export interface AppState {
    listItems: HeroListItem[];
}

export class App extends React.Component<AppProps, AppState> {
    constructor(props, context) {
        super(props, context);
        this.state = {
            listItems: []
        };
    }

    componentDidMount() {
        this.setState({
            listItems: [
                {
                    icon: 'Ribbon',
                    primaryText: 'Achieve more with Office integration'
                },
                {
                    icon: 'Unlock',
                    primaryText: 'Unlock features and functionality'
                },
                {
                    icon: 'Design',
                    primaryText: 'Create and visualize like a pro'
                }
            ]
        });
    }

    click = async () => {
        <% if (host === 'Outlook') { %>
        <%# Outlook doesn't expose Outlook.run(), so don't put that in %>
        /**
         * Insert your <%= host %> code here
         */
        <% } else { %>
        await <%= host %>.run(async (context) => {
            /**
             * Insert your <%= host %> code here
             */
            await context.sync();
        });
        <% } %>
    }

    render() {
        return (
            <div className='ms-welcome'>
                <Header logo='assets/logo-filled.png' title={this.props.title} message='Welcome' />
                <HeroList message='Discover what <%= projectDisplayName %> can do for you today!' items={this.state.listItems}>
                    <p className='ms-font-l'>Modify the source files, then click <b>Run</b>.</p>
                    <Button className='ms-welcome__action' buttonType={ButtonType.hero} icon='ChevronRight' onClick={this.click}>Run</Button>
                </HeroList>
            </div>
        );
    };
};
